# name and ip:port should be unique
# to add more peers or clients: add new lines following the same structure
peers:
  - name: 1
    address: 10.156.33.140:10000
  - name: 2
    address: 10.156.33.141:10001
  - name: 3
    address: 10.156.33.142:10002
clients:
  - name: 11
    address: 10.156.33.145:11000
  - name: 12
    address: 10.156.33.146:11001
  - name: 13
    address: 10.156.33.147:11002