// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: proto/mempool.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MemPoolMini struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender   int32                      `protobuf:"varint,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver int32                      `protobuf:"varint,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	UniqueId string                     `protobuf:"bytes,3,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
	Type     int32                      `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Note     string                     `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
	Commands []*MemPoolMini_ClientBatch `protobuf:"bytes,6,rep,name=commands,proto3" json:"commands,omitempty"`
	Creator  int32                      `protobuf:"varint,7,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (x *MemPoolMini) Reset() {
	*x = MemPoolMini{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mempool_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemPoolMini) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemPoolMini) ProtoMessage() {}

func (x *MemPoolMini) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemPoolMini.ProtoReflect.Descriptor instead.
func (*MemPoolMini) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{0}
}

func (x *MemPoolMini) GetSender() int32 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *MemPoolMini) GetReceiver() int32 {
	if x != nil {
		return x.Receiver
	}
	return 0
}

func (x *MemPoolMini) GetUniqueId() string {
	if x != nil {
		return x.UniqueId
	}
	return ""
}

func (x *MemPoolMini) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *MemPoolMini) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *MemPoolMini) GetCommands() []*MemPoolMini_ClientBatch {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *MemPoolMini) GetCreator() int32 {
	if x != nil {
		return x.Creator
	}
	return 0
}

type MemPool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender   int32  `protobuf:"varint,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver int32  `protobuf:"varint,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	UniqueId string `protobuf:"bytes,3,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
	Type     int32  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	//
	//Mem-Pool-Mem-Block 1
	//Mem-Pool-Mem-Block-Ack 2
	//Mem-Pool-Mem-Block-Request 3
	//Mem-Pool-Mem-Block-Response 4
	Note          string                        `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
	Minimemblocks []*MemPool_SingleMiniMemBlock `protobuf:"bytes,6,rep,name=minimemblocks,proto3" json:"minimemblocks,omitempty"`
	RoundNumber   int64                         `protobuf:"varint,7,opt,name=roundNumber,proto3" json:"roundNumber,omitempty"`
	ParentBlockId string                        `protobuf:"bytes,8,opt,name=parentBlockId,proto3" json:"parentBlockId,omitempty"`
	Creator       int32                         `protobuf:"varint,9,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (x *MemPool) Reset() {
	*x = MemPool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mempool_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemPool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemPool) ProtoMessage() {}

func (x *MemPool) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemPool.ProtoReflect.Descriptor instead.
func (*MemPool) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{1}
}

func (x *MemPool) GetSender() int32 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *MemPool) GetReceiver() int32 {
	if x != nil {
		return x.Receiver
	}
	return 0
}

func (x *MemPool) GetUniqueId() string {
	if x != nil {
		return x.UniqueId
	}
	return ""
}

func (x *MemPool) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *MemPool) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *MemPool) GetMinimemblocks() []*MemPool_SingleMiniMemBlock {
	if x != nil {
		return x.Minimemblocks
	}
	return nil
}

func (x *MemPool) GetRoundNumber() int64 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

func (x *MemPool) GetParentBlockId() string {
	if x != nil {
		return x.ParentBlockId
	}
	return ""
}

func (x *MemPool) GetCreator() int32 {
	if x != nil {
		return x.Creator
	}
	return 0
}

type MemPoolMini_SingleOperation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UniqueId string `protobuf:"bytes,1,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
	Command  string `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
}

func (x *MemPoolMini_SingleOperation) Reset() {
	*x = MemPoolMini_SingleOperation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mempool_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemPoolMini_SingleOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemPoolMini_SingleOperation) ProtoMessage() {}

func (x *MemPoolMini_SingleOperation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemPoolMini_SingleOperation.ProtoReflect.Descriptor instead.
func (*MemPoolMini_SingleOperation) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MemPoolMini_SingleOperation) GetUniqueId() string {
	if x != nil {
		return x.UniqueId
	}
	return ""
}

func (x *MemPoolMini_SingleOperation) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type MemPoolMini_ClientBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commands []*MemPoolMini_SingleOperation `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	Id       string                         `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Creator  int32                          `protobuf:"varint,3,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (x *MemPoolMini_ClientBatch) Reset() {
	*x = MemPoolMini_ClientBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mempool_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemPoolMini_ClientBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemPoolMini_ClientBatch) ProtoMessage() {}

func (x *MemPoolMini_ClientBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemPoolMini_ClientBatch.ProtoReflect.Descriptor instead.
func (*MemPoolMini_ClientBatch) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{0, 1}
}

func (x *MemPoolMini_ClientBatch) GetCommands() []*MemPoolMini_SingleOperation {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *MemPoolMini_ClientBatch) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MemPoolMini_ClientBatch) GetCreator() int32 {
	if x != nil {
		return x.Creator
	}
	return 0
}

type MemPool_SingleMiniMemBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UniqueId string `protobuf:"bytes,1,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
	Creator  int32  `protobuf:"varint,2,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (x *MemPool_SingleMiniMemBlock) Reset() {
	*x = MemPool_SingleMiniMemBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mempool_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemPool_SingleMiniMemBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemPool_SingleMiniMemBlock) ProtoMessage() {}

func (x *MemPool_SingleMiniMemBlock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mempool_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemPool_SingleMiniMemBlock.ProtoReflect.Descriptor instead.
func (*MemPool_SingleMiniMemBlock) Descriptor() ([]byte, []int) {
	return file_proto_mempool_proto_rawDescGZIP(), []int{1, 0}
}

func (x *MemPool_SingleMiniMemBlock) GetUniqueId() string {
	if x != nil {
		return x.UniqueId
	}
	return ""
}

func (x *MemPool_SingleMiniMemBlock) GetCreator() int32 {
	if x != nil {
		return x.Creator
	}
	return 0
}

var File_proto_mempool_proto protoreflect.FileDescriptor

var file_proto_mempool_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x6d, 0x70, 0x6f, 0x6f, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x93, 0x03, 0x0a, 0x0b, 0x4d, 0x65, 0x6d, 0x50, 0x6f, 0x6f,
	0x6c, 0x4d, 0x69, 0x6e, 0x69, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a,
	0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x6e, 0x69,
	0x71, 0x75, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x6e,
	0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f,
	0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x12, 0x34,
	0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x4d, 0x65, 0x6d, 0x50, 0x6f, 0x6f, 0x6c, 0x4d, 0x69, 0x6e, 0x69, 0x2e, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x1a, 0x48,
	0x0a, 0x0f, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x1a, 0x71, 0x0a, 0x0b, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x38, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x4d, 0x65, 0x6d, 0x50,
	0x6f, 0x6f, 0x6c, 0x4d, 0x69, 0x6e, 0x69, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x22, 0xf4, 0x02, 0x0a, 0x07,
	0x4d, 0x65, 0x6d, 0x50, 0x6f, 0x6f, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x75,
	0x6e, 0x69, 0x71, 0x75, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x6f, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65,
	0x12, 0x41, 0x0a, 0x0d, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x65, 0x6d, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x4d, 0x65, 0x6d, 0x50, 0x6f, 0x6f,
	0x6c, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x4d, 0x69, 0x6e, 0x69, 0x4d, 0x65, 0x6d, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x0d, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x65, 0x6d, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x61,
	0x72, 0x65, 0x6e, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x6f, 0x72, 0x1a, 0x4b, 0x0a, 0x12, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x4d,
	0x69, 0x6e, 0x69, 0x4d, 0x65, 0x6d, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x1b, 0x0a, 0x09, 0x75,
	0x6e, 0x69, 0x71, 0x75, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x6f, 0x72, 0x42, 0x08, 0x5a, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_mempool_proto_rawDescOnce sync.Once
	file_proto_mempool_proto_rawDescData = file_proto_mempool_proto_rawDesc
)

func file_proto_mempool_proto_rawDescGZIP() []byte {
	file_proto_mempool_proto_rawDescOnce.Do(func() {
		file_proto_mempool_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_mempool_proto_rawDescData)
	})
	return file_proto_mempool_proto_rawDescData
}

var file_proto_mempool_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_mempool_proto_goTypes = []interface{}{
	(*MemPoolMini)(nil),                 // 0: MemPoolMini
	(*MemPool)(nil),                     // 1: MemPool
	(*MemPoolMini_SingleOperation)(nil), // 2: MemPoolMini.SingleOperation
	(*MemPoolMini_ClientBatch)(nil),     // 3: MemPoolMini.ClientBatch
	(*MemPool_SingleMiniMemBlock)(nil),  // 4: MemPool.SingleMiniMemBlock
}
var file_proto_mempool_proto_depIdxs = []int32{
	3, // 0: MemPoolMini.commands:type_name -> MemPoolMini.ClientBatch
	4, // 1: MemPool.minimemblocks:type_name -> MemPool.SingleMiniMemBlock
	2, // 2: MemPoolMini.ClientBatch.commands:type_name -> MemPoolMini.SingleOperation
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_mempool_proto_init() }
func file_proto_mempool_proto_init() {
	if File_proto_mempool_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_mempool_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemPoolMini); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mempool_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemPool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mempool_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemPoolMini_SingleOperation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mempool_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemPoolMini_ClientBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mempool_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemPool_SingleMiniMemBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_mempool_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_mempool_proto_goTypes,
		DependencyIndexes: file_proto_mempool_proto_depIdxs,
		MessageInfos:      file_proto_mempool_proto_msgTypes,
	}.Build()
	File_proto_mempool_proto = out.File
	file_proto_mempool_proto_rawDesc = nil
	file_proto_mempool_proto_goTypes = nil
	file_proto_mempool_proto_depIdxs = nil
}
